import Navbar from "@/components/Navbar";
import { AuthProvider } from "./Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import ThemeProvider from "@/theme/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider>
            <Navbar />
            {/* Place your Navbar here so it has access to the session */}
            {children} {/* This is where your page content will be rendered */}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
